export const users = [
  // admins
  {
    id: '1',
    name: 'Dan',
    avatar: '/images/profile.gif',
    handle: '@dan',
    role: 'admin',
    postsCount: 3,
    status: 'active',
  },
  {
    id: '11',
    name: 'Ben',
    avatar: '/images/avatar_ben.gif',
    handle: '@ben',
    role: 'admin',
    postsCount: 15,
    status: 'active',
  },
  {
    id: '12',
    name: 'Karly',
    avatar: '/images/avatar_karly.gif',
    handle: '@karly',
    role: 'admin',
    postsCount: 19,
    status: 'active',
  },
  // creators
  {
    id: '2',
    name: 'Paulie Gualtieri',
    avatar: '/images/avatar_1.gif',
    handle: '@paulie',
    role: 'creator',
    postsCount: 14,
    status: 'active',
  },
  {
    id: '3',
    name: 'Adriana La Cerva',
    avatar: '/images/avatar_adriana.gif',
    handle: '@adriana',
    role: 'creator',
    postsCount: 9,
    status: 'active',
  },
  {
    id: '6',
    name: 'Christopher Moltisanti',
    avatar: '/images/avatar_5.gif',
    handle: '@chrissie',
    role: 'creator',
    postsCount: 7,
    status: 'active',
  },
  {
    id: '8',
    name: 'Furio Giunta',
    avatar: '/images/avatar_7.gif',
    handle: '@furio',
    role: 'creator',
    postsCount: 11,
    status: 'active',
  },
  {
    id: '10',
    name: 'Janice Soprano',
    avatar: '/images/avatar_9.gif',
    handle: '@janice',
    role: 'creator',
    postsCount: 5,
    status: 'inactive',
  },
  // posters
  {
    id: '4',
    name: 'Silvio Dante',
    avatar: '/images/avatar_3.gif',
    handle: '@silvio',
    role: 'poster',
    postsCount: 22,
    status: 'active',
  },
  {
    id: '5',
    name: 'Carmela Soprano',
    avatar: '/images/avatar_4.gif',
    handle: '@carmela',
    role: 'poster',
    postsCount: 18,
    status: 'inactive',
  },
  {
    id: '7',
    name: 'Bobby Baccala',
    avatar: '/images/avatar_6.gif',
    handle: '@bobby',
    role: 'poster',
    postsCount: 31,
    status: 'active',
  },
  {
    id: '9',
    name: 'Vito Spatafore',
    avatar: '/images/avatar_8.gif',
    handle: '@vito',
    role: 'poster',
    postsCount: 26,
    status: 'active',
  },
]

export const posts = [
  {
    id: '1',
    title: 'Summer Vibes Collection',
    type: 'slideshow',
    status: 'posted',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/posts/post_1.jpg',
    createdBy: '2',
    createdAt: '2026-03-10T14:30:00Z',
    scheduledFor: '2026-03-10T18:00:00Z',
    assignedTo: '4',
  },
  {
    id: '2',
    title: 'Product Launch Teaser',
    type: 'reel',
    status: 'queued',
    platforms: ['instagram', 'tiktok', 'youtube'],
    thumbnail: '/images/posts/post_2.jpg',
    createdBy: '3',
    createdAt: '2026-03-09T10:00:00Z',
    scheduledFor: '2026-03-12T12:00:00Z',
    assignedTo: '4',
  },
  {
    id: '3',
    title: 'Behind the Scenes',
    type: 'image',
    status: 'ready',
    platforms: ['instagram'],
    thumbnail: '/images/posts/post_3.jpg',
    createdBy: '2',
    createdAt: '2026-03-08T16:45:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '4',
    title: 'Weekly Roundup #12',
    type: 'slideshow',
    status: 'ready',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/posts/post_4.jpg',
    createdBy: '3',
    createdAt: '2026-03-08T09:20:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '5',
    title: 'New Feature Spotlight',
    type: 'reel',
    status: 'draft',
    platforms: ['tiktok', 'youtube'],
    thumbnail: '/images/posts/post_5.jpg',
    createdBy: '6',
    createdAt: '2026-03-07T11:00:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '6',
    title: 'Team Introduction',
    type: 'reel',
    status: 'draft',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/posts/post_1.jpg',
    createdBy: '8',
    createdAt: '2026-03-07T08:30:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '7',
    title: 'Style Guide Preview',
    type: 'image',
    status: 'draft',
    platforms: ['instagram'],
    thumbnail: '/images/posts/post_2.jpg',
    createdBy: '2',
    createdAt: '2026-03-06T15:00:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '8',
    title: 'March Campaign Opener',
    type: 'slideshow',
    status: 'posted',
    platforms: ['instagram', 'tiktok', 'youtube'],
    thumbnail: '/images/posts/post_3.jpg',
    createdBy: '3',
    createdAt: '2026-03-05T10:00:00Z',
    scheduledFor: '2026-03-06T09:00:00Z',
    assignedTo: '7',
  },
  {
    id: '9',
    title: 'Brand Story Part 1',
    type: 'reel',
    status: 'posted',
    platforms: ['tiktok'],
    thumbnail: '/images/posts/post_4.jpg',
    createdBy: '6',
    createdAt: '2026-03-04T14:00:00Z',
    scheduledFor: '2026-03-05T16:00:00Z',
    assignedTo: '9',
  },
  {
    id: '10',
    title: 'Q1 Recap Montage',
    type: 'reel',
    status: 'queued',
    platforms: ['youtube', 'tiktok'],
    thumbnail: '/images/posts/post_5.jpg',
    createdBy: '8',
    createdAt: '2026-03-03T09:00:00Z',
    scheduledFor: '2026-03-13T10:00:00Z',
    assignedTo: '9',
  },
  {
    id: '11',
    title: 'Minimalist Mood Board',
    type: 'image',
    status: 'posted',
    platforms: ['instagram'],
    thumbnail: '/images/posts/post_1.jpg',
    createdBy: '10',
    createdAt: '2026-03-02T13:00:00Z',
    scheduledFor: '2026-03-03T08:00:00Z',
    assignedTo: '4',
  },
  {
    id: '12',
    title: 'Creator Spotlight: Kai',
    type: 'slideshow',
    status: 'ready',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/posts/post_2.jpg',
    createdBy: '6',
    createdAt: '2026-03-01T17:00:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '13',
    title: 'Late Night Edits',
    type: 'reel',
    status: 'draft',
    platforms: ['tiktok'],
    thumbnail: '/images/posts/post_3.jpg',
    createdBy: '8',
    createdAt: '2026-02-28T23:30:00Z',
    scheduledFor: null,
    assignedTo: null,
  },
  {
    id: '14',
    title: 'Platform Strategy Breakdown',
    type: 'slideshow',
    status: 'posted',
    platforms: ['instagram', 'youtube'],
    thumbnail: '/images/posts/post_4.jpg',
    createdBy: '3',
    createdAt: '2026-02-27T10:00:00Z',
    scheduledFor: '2026-02-28T12:00:00Z',
    assignedTo: '7',
  },
]

export const menuItems = [
  { icon: 'PhHouse', label: 'Dashboard', path: '/', roles: ['admin', 'creator', 'poster'] },
  { icon: 'PhPencilLine', label: 'Create', path: '/create', roles: ['admin', 'creator'] },
  { icon: 'PhTray', label: 'Queue', path: '/queue', roles: ['admin', 'creator', 'poster'] },
  { icon: 'PhCalendarBlank', label: 'Calendar', path: '/calendar', roles: ['admin', 'poster'] },
  { icon: 'PhUsersThree', label: 'Team', path: '/team', roles: ['admin'] },
  { icon: 'PhGear', label: 'Settings', path: '/settings', roles: ['admin', 'creator', 'poster'] },
]

export const activityFeed = [
  { userId: '2', action: 'Created "Summer Vibes Collection"', time: '2 min ago' },
  { userId: '7', action: 'Posted "March Campaign Opener" to Instagram', time: '15 min ago' },
  { userId: '3', action: 'Created "Product Launch Teaser"', time: '1 hour ago' },
  { userId: '9', action: 'Claimed "Weekly Roundup #12"', time: '3 hours ago' },
  { userId: '6', action: 'Uploaded "Brand Story Part 1"', time: '4 hours ago' },
  { userId: '8', action: 'Created "Team Introduction"', time: '5 hours ago' },
  { userId: '10', action: 'Drafted "Minimalist Mood Board"', time: '6 hours ago' },
  { userId: '4', action: 'Posted "Q1 Recap" to TikTok', time: '8 hours ago' },
]
