export const posts = [
  {
    id: '1',
    title: 'Summer Vibes Collection',
    type: 'slideshow',
    status: 'posted',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/asset_1.jpg',
    createdBy: '2',
    createdAt: '2026-03-10T14:30:00Z',
    scheduledFor: '2026-03-10T18:00:00Z',
    assignedTo: '4',
    platform: 'instagram',
  },
  {
    id: '2',
    title: 'Product Launch Teaser',
    type: 'reel',
    status: 'queued',
    platforms: ['instagram', 'tiktok', 'youtube'],
    thumbnail: '/images/asset_2.jpg',
    createdBy: '3',
    createdAt: '2026-03-09T10:00:00Z',
    scheduledFor: '2026-03-12T12:00:00Z',
    assignedTo: '4',
    platform: 'tiktok',
  },
  {
    id: '3',
    title: 'Behind the Scenes',
    type: 'image',
    status: 'ready',
    platforms: ['instagram'],
    thumbnail: '/images/asset_3.jpg',
    createdBy: '2',
    createdAt: '2026-03-08T16:45:00Z',
    scheduledFor: null,
    assignedTo: null,
    platform: null,
  },
  {
    id: '4',
    title: 'Weekly Roundup #12',
    type: 'slideshow',
    status: 'ready',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/asset_4.jpg',
    createdBy: '3',
    createdAt: '2026-03-08T09:20:00Z',
    scheduledFor: null,
    assignedTo: null,
    platform: null,
  },
  {
    id: '5',
    title: 'New Feature Spotlight',
    type: 'reel',
    status: 'draft',
    platforms: ['tiktok', 'youtube'],
    thumbnail: '/images/asset_5.jpg',
    createdBy: '2',
    createdAt: '2026-03-07T11:00:00Z',
    scheduledFor: null,
    assignedTo: null,
    platform: null,
  },
  {
    id: '6',
    title: 'Team Introduction',
    type: 'reel',
    status: 'draft',
    platforms: ['instagram', 'tiktok'],
    thumbnail: '/images/asset_7.jpg',
    createdBy: '3',
    createdAt: '2026-03-07T08:30:00Z',
    scheduledFor: null,
    assignedTo: null,
    platform: null,
  },
  {
    id: '7',
    title: 'Style Guide Preview',
    type: 'image',
    status: 'draft',
    platforms: ['instagram'],
    thumbnail: '/images/asset_8.jpg',
    createdBy: '2',
    createdAt: '2026-03-06T15:00:00Z',
    scheduledFor: null,
    assignedTo: null,
    platform: null,
  },
  {
    id: '8',
    title: 'March Campaign Opener',
    type: 'slideshow',
    status: 'posted',
    platforms: ['instagram', 'tiktok', 'youtube'],
    thumbnail: '/images/asset_9.jpg',
    createdBy: '3',
    createdAt: '2026-03-05T10:00:00Z',
    scheduledFor: '2026-03-06T09:00:00Z',
    assignedTo: '5',
    platform: 'instagram',
  },
  {
    id: '9',
    title: 'Brand Story Part 1',
    type: 'reel',
    status: 'posted',
    platforms: ['tiktok'],
    thumbnail: '/images/asset_10.jpg',
    createdBy: '2',
    createdAt: '2026-03-04T14:00:00Z',
    scheduledFor: '2026-03-05T16:00:00Z',
    assignedTo: '4',
    platform: 'tiktok',
  },
]

export const teamMembers = [
  {
    id: '1',
    name: 'Dan',
    avatar: '/images/asset_6.jpg',
    handle: '@dan',
    role: 'admin',
    postsCount: 0,
    status: 'active',
  },
  {
    id: '2',
    name: 'Juan Pedro',
    avatar: '/images/asset_7.jpg',
    handle: '@vallejo',
    role: 'creator',
    postsCount: 14,
    status: 'active',
  },
  {
    id: '3',
    name: 'Sara Chen',
    avatar: '/images/asset_8.jpg',
    handle: '@sarachen',
    role: 'creator',
    postsCount: 9,
    status: 'active',
  },
  {
    id: '4',
    name: 'Marcus Bell',
    avatar: '/images/asset_9.jpg',
    handle: '@marcusbell',
    role: 'poster',
    postsCount: 22,
    status: 'active',
  },
  {
    id: '5',
    name: 'Lina Torres',
    avatar: '/images/asset_10.jpg',
    handle: '@linatorres',
    role: 'poster',
    postsCount: 18,
    status: 'inactive',
  },
]

export const menuItems = [
  { icon: 'PhHouse', label: 'Dashboard', path: '/', roles: ['admin', 'creator', 'poster'] },
  { icon: 'PhPencilLine', label: 'Create', path: '/create', roles: ['admin', 'creator'] },
  { icon: 'PhTray', label: 'Queue', path: '/queue', roles: ['admin', 'creator', 'poster'] },
  { icon: 'PhCalendarBlank', label: 'Calendar', path: '/calendar', roles: ['admin', 'poster'] },
  { icon: 'PhUsersThree', label: 'Team', path: '/team', roles: ['admin'] },
  { icon: 'PhGear', label: 'Settings', path: '/settings', roles: ['admin', 'creator', 'poster'] },
]

export const activityFeed = [
  { userId: '2', action: 'Created "Summer Vibes Collection"', time: '2 min ago' },
  { userId: '4', action: 'Posted "March Campaign Opener" to Instagram', time: '15 min ago' },
  { userId: '3', action: 'Created "Product Launch Teaser"', time: '1 hour ago' },
  { userId: '5', action: 'Claimed "Weekly Roundup #12"', time: '3 hours ago' },
]
