export const assetCards = [
  {
    id: '1',
    image: '/images/asset_1.jpg',
    collection: 'WGMinterfaces',
    tokenId: '#983',
    price: 2,
    rating: 9,
  },
  {
    id: '2',
    image: '/images/asset_2.jpg',
    collection: 'WGMinterfaces',
    tokenId: '#2931',
    price: 1.9,
    rating: 9.6,
  },
  {
    id: '3',
    image: '/images/asset_3.jpg',
    collection: 'WGMinterfaces',
    tokenId: '#1332',
    price: 1.2,
    rating: 9.2,
  },
  {
    id: '4',
    image: '/images/asset_4.jpg',
    collection: 'WGMinterfaces',
    tokenId: '#2132',
    price: 0.3,
    rating: 9.2,
  },
]

export const creators = [
  {
    id: '1',
    avatar: '/images/asset_7.jpg',
    name: 'Juan Pedro',
    handle: '@Vallejo',
    volume: 8300.10,
    flowPrice: 10.1,
    status: -1.20,
    owners: '12.1K',
    items: '5.0K',
  },
  {
    id: '2',
    avatar: '/images/asset_8.jpg',
    name: 'BananaCandy',
    handle: '@bananacandynft',
    volume: 7930.00,
    flowPrice: 2.32,
    status: 65.31,
    owners: '12.1K',
    items: '5.0K',
  },
  {
    id: '3',
    avatar: '/images/asset_9.jpg',
    name: 'CharmingStudio',
    handle: '@charmingStudio',
    volume: 7543.23,
    flowPrice: 32.12,
    status: -2.15,
    owners: '12.1K',
    items: '5.0K',
  },
  {
    id: '4',
    avatar: '/images/asset_10.jpg',
    name: 'Black Steve',
    handle: '@Theblackartist',
    volume: 7210.15,
    flowPrice: 8.23,
    status: -20.00,
    owners: '12.1K',
    items: '5.0K',
  },
]

export const menuItems = [
  { icon: 'PhHouse', label: 'Dashboard', path: '/' },
  { icon: 'PhChartBar', label: 'User Analytics', path: '/user-analytics', badge: 'D' },
  { icon: 'PhHeart', label: 'VIP Collections', path: '/vip-collections' },
  { icon: 'PhUsers', label: 'Invitation', path: '/invitation' },
  { icon: 'PhGear', label: 'Settings', path: '/settings' },
  { icon: 'PhBell', label: 'Notification', path: '/notification' },
  { icon: 'PhDiamond', label: 'Subscription', path: '/subscription' },
  { icon: 'PhLightning', label: 'Promotion', path: '/promotion' },
]
